name: CI

on: push

jobs:
  CI:
    runs-on: ubuntu-latest
    container: python:3.7.7-buster
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
      - name: Check formatting
        run: make check-fmt
      - name: Run tests
        run: make tests
